"""Initial migration: users, roles, brands, brand_kpis tables

Revision ID: 78b0f89c9ad8
Revises: 
Create Date: 2025-10-23 16:43:14.129945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b0f89c9ad8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('slogan', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tone_manner', sa.JSON(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_brand_name'), 'brands', ['brand_name'], unique=False)
    op.create_index(op.f('ix_brands_category'), 'brands', ['category'], unique=False)
    op.create_index(op.f('ix_brands_created_at'), 'brands', ['created_at'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_user_id'), 'brands', ['user_id'], unique=False)
    op.create_table('brand_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('kpi_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('measurement_date', sa.DateTime(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('avg_views', sa.Integer(), nullable=True),
    sa.Column('avg_likes', sa.Integer(), nullable=True),
    sa.Column('avg_comments', sa.Integer(), nullable=True),
    sa.Column('popularity_index', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_kpis_brand_id'), 'brand_kpis', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brand_kpis_id'), 'brand_kpis', ['id'], unique=False)
    op.create_index(op.f('ix_brand_kpis_kpi_type'), 'brand_kpis', ['kpi_type'], unique=False)
    op.create_index(op.f('ix_brand_kpis_measurement_date'), 'brand_kpis', ['measurement_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_kpis_measurement_date'), table_name='brand_kpis')
    op.drop_index(op.f('ix_brand_kpis_kpi_type'), table_name='brand_kpis')
    op.drop_index(op.f('ix_brand_kpis_id'), table_name='brand_kpis')
    op.drop_index(op.f('ix_brand_kpis_brand_id'), table_name='brand_kpis')
    op.drop_table('brand_kpis')
    op.drop_index(op.f('ix_brands_user_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_created_at'), table_name='brands')
    op.drop_index(op.f('ix_brands_category'), table_name='brands')
    op.drop_index(op.f('ix_brands_brand_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
