"""Add Back2 and Back3 models (Insight, Report, Design, Campaign)

Revision ID: a20fed5e3788
Revises: 78b0f89c9ad8
Create Date: 2025-10-24 11:08:23.608593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20fed5e3788'
down_revision: Union[str, None] = '78b0f89c9ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False, comment='사용자 입력 프롬프트'),
    sa.Column('insight_type', sa.Enum('MARKET_ANALYSIS', 'KEYWORD_CLUSTERING', 'INFLUENCER_RECOMMENDATION', 'VISUAL_PROPOSAL', 'ITEM_SUGGESTION', name='insighttype'), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=True, comment='AI 분석 요약'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='추출된 키워드 리스트'),
    sa.Column('market_data', sa.JSON(), nullable=True, comment='시장 데이터'),
    sa.Column('recommendations', sa.JSON(), nullable=True, comment='추천 사항'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_insights_id'), 'brand_insights', ['id'], unique=False)
    op.create_table('brand_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=True, comment='리포트 유형'),
    sa.Column('overall_score', sa.Float(), nullable=True, comment='전체 점수 (0-100)'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI 생성 요약'),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True, comment='AI 개선 제안'),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='생성된 PDF URL'),
    sa.Column('pdf_language', sa.String(length=10), nullable=True, comment='리포트 언어 (ko/en)'),
    sa.Column('pdf_color_scheme', sa.String(length=50), nullable=True, comment='컬러 스킴'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_reports_id'), 'brand_reports', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.Enum('SNS', 'INFLUENCER', 'EMAIL', 'CONTENT', 'MIXED', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True, comment='캠페인 목표'),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True, comment='예산'),
    sa.Column('budget_currency', sa.String(length=10), nullable=True, comment='통화'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='시작일'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='종료일'),
    sa.Column('target_audience', sa.JSON(), nullable=True, comment='타겟 오디언스'),
    sa.Column('target_keywords', sa.JSON(), nullable=True, comment='타겟 키워드'),
    sa.Column('ai_budget_recommendation', sa.JSON(), nullable=True, comment='AI 예산 추천'),
    sa.Column('ai_influencer_recommendations', sa.JSON(), nullable=True, comment='AI 인플루언서 추천'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('shortform_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('input_type', sa.Enum('IMPORT', 'SCRIPT', 'BLANK', name='designinputtype'), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=True, comment='스크립트 텍스트'),
    sa.Column('script_file_url', sa.String(length=500), nullable=True, comment='업로드된 스크립트 파일 URL'),
    sa.Column('num_cuts', sa.Integer(), nullable=True, comment='컷 수'),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True, comment='영상 비율'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='언어'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortform_projects_id'), 'shortform_projects', ['id'], unique=False)
    op.create_table('brand_diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('MARKET', 'COMPETITOR', 'MANUFACTURING', 'BRAND', 'MARKETING', name='diagnosticsection'), nullable=False),
    sa.Column('questions_answers', sa.JSON(), nullable=False, comment='질문-응답 데이터'),
    sa.Column('section_score', sa.Float(), nullable=True, comment='섹션 점수 (0-100)'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='AI 분석 코멘트'),
    sa.Column('strengths', sa.JSON(), nullable=True, comment='강점'),
    sa.Column('weaknesses', sa.JSON(), nullable=True, comment='약점'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['brand_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_diagnostics_id'), 'brand_diagnostics', ['id'], unique=False)
    op.create_table('campaign_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('report_month', sa.String(length=7), nullable=False, comment='리포트 월 (YYYY-MM)'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=True, comment='총 매출'),
    sa.Column('total_sales', sa.Integer(), nullable=True, comment='총 판매량'),
    sa.Column('total_products', sa.Integer(), nullable=True, comment='총 상품수'),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='총 비용'),
    sa.Column('top_campaigns', sa.JSON(), nullable=True, comment='상위 캠페인'),
    sa.Column('top_customers', sa.JSON(), nullable=True, comment='상위 고객'),
    sa.Column('top_products', sa.JSON(), nullable=True, comment='상위 제품'),
    sa.Column('channel_performance', sa.JSON(), nullable=True, comment='채널별 성과'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI 요약'),
    sa.Column('ai_predictions', sa.JSON(), nullable=True, comment='AI 성과 예측'),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True, comment='AI 개선 제안'),
    sa.Column('social_performance', sa.JSON(), nullable=True, comment='SNS 유입 비율 및 성과'),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='PDF URL'),
    sa.Column('excel_url', sa.String(length=500), nullable=True, comment='Excel URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_reports_id'), 'campaign_reports', ['id'], unique=False)
    op.create_table('campaign_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('tracking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True, comment='노출수'),
    sa.Column('clicks', sa.Integer(), nullable=True, comment='클릭수'),
    sa.Column('conversions', sa.Integer(), nullable=True, comment='전환수'),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True, comment='매출'),
    sa.Column('cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='비용'),
    sa.Column('ctr', sa.Float(), nullable=True, comment='CTR (Click-Through Rate)'),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True, comment='CPC (Cost Per Click)'),
    sa.Column('roas', sa.Float(), nullable=True, comment='ROAS (Return on Ad Spend)'),
    sa.Column('likes', sa.Integer(), nullable=True, comment='좋아요'),
    sa.Column('shares', sa.Integer(), nullable=True, comment='공유'),
    sa.Column('comments', sa.Integer(), nullable=True, comment='댓글'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_tracking_id'), 'campaign_tracking', ['id'], unique=False)
    op.create_table('design_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('input_type', sa.Enum('IMPORT', 'SCRIPT', 'BLANK', name='designinputtype'), nullable=False),
    sa.Column('tone_manner', sa.JSON(), nullable=True, comment='톤앤매너 차트 데이터'),
    sa.Column('color_palette', sa.JSON(), nullable=True, comment='컬러 팔레트'),
    sa.Column('prompt', sa.Text(), nullable=True, comment='디자인 프롬프트'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='디자인 키워드'),
    sa.Column('bid_report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bid_report_id'], ['brand_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_projects_id'), 'design_projects', ['id'], unique=False)
    op.create_table('insight_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True, comment='결과 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='결과 설명'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='결과 카테고리'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='신뢰도 점수 (0-100)'),
    sa.Column('data', sa.JSON(), nullable=True, comment='상세 데이터'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='이미지 URL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['brand_insights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_results_id'), 'insight_results', ['id'], unique=False)
    op.create_table('report_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False, comment='섹션명 (타겟/키워드/매니징/디자인/마케팅)'),
    sa.Column('section_order', sa.Integer(), nullable=True, comment='섹션 순서'),
    sa.Column('content', sa.JSON(), nullable=True, comment='섹션 콘텐츠 데이터'),
    sa.Column('chart_data', sa.JSON(), nullable=True, comment='차트 데이터'),
    sa.Column('insights', sa.JSON(), nullable=True, comment='인사이트 데이터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['brand_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sections_id'), 'report_sections', ['id'], unique=False)
    op.create_table('storyboard_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False, comment='프레임 번호'),
    sa.Column('dialogue', sa.Text(), nullable=True, comment='대사/텍스트'),
    sa.Column('shooting_note', sa.Text(), nullable=True, comment='촬영 노트'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='생성된 이미지 URL'),
    sa.Column('image_prompt', sa.Text(), nullable=True, comment='이미지 생성 프롬프트'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['shortform_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboard_frames_id'), 'storyboard_frames', ['id'], unique=False)
    op.create_table('design_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='생성된 이미지 URL'),
    sa.Column('ideogram_id', sa.String(length=200), nullable=True, comment='Ideogram API 이미지 ID'),
    sa.Column('generation_prompt', sa.Text(), nullable=True, comment='실제 사용된 프롬프트'),
    sa.Column('style', sa.String(length=100), nullable=True, comment='스타일'),
    sa.Column('industry_category', sa.String(length=100), nullable=True, comment='산업 카테고리'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['design_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_results_id'), 'design_results', ['id'], unique=False)
    op.create_table('design_mockups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_result_id', sa.Integer(), nullable=False),
    sa.Column('mockup_type', sa.String(length=100), nullable=True, comment='목업 유형 (패키지/명함/포스터 등)'),
    sa.Column('mockup_url', sa.String(length=500), nullable=True, comment='목업 이미지 URL'),
    sa.Column('industry_tab', sa.String(length=100), nullable=True, comment='산업별 탭'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['design_result_id'], ['design_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_mockups_id'), 'design_mockups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_mockups_id'), table_name='design_mockups')
    op.drop_table('design_mockups')
    op.drop_index(op.f('ix_design_results_id'), table_name='design_results')
    op.drop_table('design_results')
    op.drop_index(op.f('ix_storyboard_frames_id'), table_name='storyboard_frames')
    op.drop_table('storyboard_frames')
    op.drop_index(op.f('ix_report_sections_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_insight_results_id'), table_name='insight_results')
    op.drop_table('insight_results')
    op.drop_index(op.f('ix_design_projects_id'), table_name='design_projects')
    op.drop_table('design_projects')
    op.drop_index(op.f('ix_campaign_tracking_id'), table_name='campaign_tracking')
    op.drop_table('campaign_tracking')
    op.drop_index(op.f('ix_campaign_reports_id'), table_name='campaign_reports')
    op.drop_table('campaign_reports')
    op.drop_index(op.f('ix_brand_diagnostics_id'), table_name='brand_diagnostics')
    op.drop_table('brand_diagnostics')
    op.drop_index(op.f('ix_shortform_projects_id'), table_name='shortform_projects')
    op.drop_table('shortform_projects')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_brand_reports_id'), table_name='brand_reports')
    op.drop_table('brand_reports')
    op.drop_index(op.f('ix_brand_insights_id'), table_name='brand_insights')
    op.drop_table('brand_insights')
    # ### end Alembic commands ###
